volumes:
    sql-server:

services:     
    sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        container_name: sql-server
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=sa@@2020
        ports:
            - "1433:1433"
        volumes: 
            - sql-server:/var/opt/mssql
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -U sa -P $$SA_PASSWORD -Q "SELECT 1"

    net-core-sample:
        image: net-core-sample
        container_name: net-core-sample
        build:
            context: ./src/
            dockerfile: Dockerfile
        ports:
          - "8080:80"
        depends_on:
          sql-server:
            condition: service_healthy