version: "3.8"

volumes:
    sql-server:

services:     
    sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest"
        environment:
            - ACCEPT_EULA=Y
            - SA_PASSWORD=sa@a2020
        ports:
            - "1433:1433"
        volumes: 
            - sql-server:/var/opt/mssql

    net-core-sample:
        build:
            context: ./
            dockerfile: Dockerfile.Api
        ports:
          - "80:80"
        environment:
            - ASPNETCORE_ENVIRONMENT=Docker
        depends_on:
          - sql-server
