kind: Service
apiVersion: v1
metadata:
  name: net-core-docker-sample-service
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  selector:
    app: net-core-docker-sample
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  type: ClusterIP
  