trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
- group: azure-devops

steps:
- task: dependabot@1
  inputs:
    packageManager: 'nuget'
    versioningStrategy: 'auto'
    failOnException: true
    gitHubConnection: 'github'
    azureDevOpsAccessToken: '$(PAT)'